version: '2'
services:
  mysql:
    image: daocloud.io/library/mysql:5.6.28
    container_name: mysql
    volumes:
      - "./data:/var/lib/mysql"
    restart: always
    environment:
      TERM: xterm
      MYSQL_ROOT_PASSWORD: 102323
#      MYSQL_DATABASE: wordpress
#      MYSQL_USER: wordpress
#      MYSQL_PASSWORD: wordpress
  php:
    build: ./php
    image: php:0.1
    container_name: php
    volumes:
      - "./site:/var/www/html"
    restart: always
    expose:
     - "9000"
     - "9001"
    environment:
      TERM: xterm

  nginx:
    image: daocloud.io/library/nginx:1.10
    container_name: nginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./conf.d:/etc/nginx/conf.d"
      - "./site:/var/www/html"
    ports:
      - "80:80"
      - "9000:9000"
      - "9001:9001"
    links:
      - mysql:db
      - php
    restart: always
    environment:
      TERM: xterm
